# Site settings
title: Rui Lan Zhang 
subtitle: Homepage
tagline: I am Rui Lan Zhang, a PhD Student at the University of Tokyo.
email: ruilan.zhang@phys.s.u-tokyo.ac.jp
description: I am Rui Lan Zhang, a PhD Student at the University of Tokyo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ruilan-zh.github.io" # the base hostname & protocol for your site
logo: assets/images/favicon.png
image: assets/images/og-pic.jpg


# Blog posts
words_per_minute : 160
future : true
read_more : "disabled"

# projects
collections:
    projects:
        output: true

myversion: 4.5.0

author:
    name: Rui Lan Zhang
    avatar : assets/images/profile_picture.png
    avatar-webp: assets/images/profile_picture.webp
    avatar-thumb: assets/images/profile_picture-thumb.jpg
    author-bio : "PhD Student at the University of Tokyo."
    ads : 
    facebook: 
    github: https://github.com/ruilan-zh
    gitlab: 
    googleplus: 
    googlescholar : 
    instagram: 
    linkedin: https://uk.linkedin.com/in/rui-lan-zhang-498b54172
    orcid: 
    pinterest:
    researchgate: 
    slack:
    stackoverflow : 
    steam : 
    twitter: 

# Social for SEO
twitter: 
  username: 
  card: 

facebook:
  app_id: 
  publisher: 
  admins:

social:
  name: Soumyadeep Das
  links:
    - https://github.com/ruilan-zh
    - https://linkedin.com/in/rui-lan-zhang-498b54172

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gzip
  - jekyll-brotli
  - jekyll-redirect-from

# Build settings
markdown: kramdown



exclude:
  - vendor  
